// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkXPllq04TYnDk8179wEgg276QNI-fMs',
    appId: '1:444657505753:web:cbb4580e7bb816feff35c8',
    messagingSenderId: '444657505753',
    projectId: 'login-register-csdl',
    authDomain: 'login-register-csdl.firebaseapp.com',
    storageBucket: 'login-register-csdl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsQOoWBoi77dCOZeSrRzFd2QTgpB128os',
    appId: '1:444657505753:android:dae79f6a173925c9ff35c8',
    messagingSenderId: '444657505753',
    projectId: 'login-register-csdl',
    storageBucket: 'login-register-csdl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAze7X2ZBLuFqFHy9kNa96Xbb8k5i00D9E',
    appId: '1:444657505753:ios:517aa3c02b1273b7ff35c8',
    messagingSenderId: '444657505753',
    projectId: 'login-register-csdl',
    storageBucket: 'login-register-csdl.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAze7X2ZBLuFqFHy9kNa96Xbb8k5i00D9E',
    appId: '1:444657505753:ios:517aa3c02b1273b7ff35c8',
    messagingSenderId: '444657505753',
    projectId: 'login-register-csdl',
    storageBucket: 'login-register-csdl.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCkXPllq04TYnDk8179wEgg276QNI-fMs',
    appId: '1:444657505753:web:8935c1e51da73a3fff35c8',
    messagingSenderId: '444657505753',
    projectId: 'login-register-csdl',
    authDomain: 'login-register-csdl.firebaseapp.com',
    storageBucket: 'login-register-csdl.firebasestorage.app',
  );
}
